apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::749664565277:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1P3MUJZIMS1BJ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::749664565277:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-04T04:27:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "112478"
  uid: b11e5daf-a373-4c08-b307-04c6ba7676a6
